return {
	{ "<leader>p", "<cmd>Telescope yank_history<cr>", mode = { "n", "x" }, desc = "Smart Yank History" },
	{ "y", "<Plug>(YankyYank)", mode = { "n", "x" }, desc = "Smart Yank text" },
	{
		"p",
		"<Plug>(YankyPutAfter)",
		mode = { "n", "x" },
		desc = "Smart Put yanked text after cursor",
	},
	{
		"P",
		"<Plug>(YankyPutBefore)",
		mode = { "n", "x" },
		desc = "Smart Put yanked text before cursor",
	},
	{
		"gp",
		"<Plug>(YankyGPutAfter)",
		mode = { "n", "x" },
		desc = "Smart Put yanked text after cursor and leave cursor after",
	},
	{
		"gP",
		"<Plug>(YankyGPutBefore)",
		mode = { "n", "x" },
		desc = "Smart Put yanked text before cursor and leave cursor after",
	},
	{ "]p", "<Plug>(YankyPutIndentAfterLinewise)", desc = "Smart Put indented after cursor (linewise)" },
	{ "[p", "<Plug>(YankyPutIndentBeforeLinewise)", desc = "Smart Put indented before cursor (linewise)" },
	{ "]P", "<Plug>(YankyPutIndentAfterLinewise)", desc = "Smart Put indented after cursor (linewise)" },
	{ "[P", "<Plug>(YankyPutIndentBeforeLinewise)", desc = "Smart Put indented before cursor (linewise)" },
	{ ">p", "<Plug>(YankyPutIndentAfterShiftRight)", desc = "Smart Put and indent right" },
	{ "<p", "<Plug>(YankyPutIndentAfterShiftLeft)", desc = "Smart Put and indent left" },
	{ ">P", "<Plug>(YankyPutIndentBeforeShiftRight)", desc = "Smart Put before and indent right" },
	{ "<P", "<Plug>(YankyPutIndentBeforeShiftLeft)", desc = "Smart Put before and indent left" },
	{ "=p", "<Plug>(YankyPutAfterFilter)", desc = "Smart Put after applying a filter" },
	{ "=P", "<Plug>(YankyPutBeforeFilter)", desc = "Smart Put before applying a filter" },
}
